bq_dbt_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: coral-hull-501505-n8
      dataset: analytics_dev
      threads: 4
      location: US
      priority: interactive
      job_execution_timeout_seconds: 300
      job_retries: 1
